name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Show Python version
      run: python --version

    - name: Show pip version
      run: pip --version

    - name: List installed packages
      run: pip list

    - name: Run tests
      run: pytest
